import Head from 'next/head';
import Image from 'next/image';
import styles from './Layout.module.css';

const Layout = ({ children, title = 'World ranks' }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Image src="/logo.svg" alt="Logo" width={175} height={24} />
      </header>

      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        this is footer
      </footer>
    </div>
  )
};

export default Layout;
